import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { io } from "socket.io-client";
import { useEffect, useState } from "react";

import React from "react";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js";
import { Line } from "react-chartjs-2";
import faker from "faker";

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

export default function Home() {
  const [products, setproducts] = useState([]);
  useEffect(() => {
    const socket = io("ws://localhost:4000", {
      path: "/chart",
    });
    socket.on("price", (...response) => {
      if (response) {
        console.log(response);
        if (products.length >= 7) {
          //products.shift();
        }
        setproducts((old) => [...old, ...response]);
      }
    });
  }, []);
  return (
    <div className={styles.container} style={{}}>
      <Head>
        <title>Product Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Chart products={products.slice(-20)} />
    </div>
  );
}

const Chart = ({ products }) => {
  const labels = products.map((p) => p.date);
  const datasets = products.length == 0 ? [] : products[0].data;

  const data = {
    labels,
    datasets: datasets.map((p, i) => ({
      label: p.product,
      data: labels.map(
        (l, i) =>
          products[i].data.filter((d) => d.product == p.product)[0].price
      ),
      borderColor: [
        "rgb(255, 99, 132)",
        "rgb(5, 9, 0)",
        "rgb(255, 99, 12)",
        "rgb(25, 0, 132)",
        "rgb(252, 929, 13)",
        "rgb(55, 99, 132)",
        "rgb(255, 99, 32)",
        "rgb(25, 99, 32)",
      ][i],
      backgroundColor: [
        "rgba(255, 99, 132,0.3)",
        "rgba(55, 99, 132,0.3)",
        "rgba(255, 99, 12,0.3)",
        "rgba(25, 0, 132,0.3)",
        "rgba(25, 99, 13,0.3)",
        "rgba(55, 99, 132,0.3)",
        "rgba(255, 99, 32,0.3)",
        "rgba(25, 99, 32,0.3)",
      ][i],
      yAxisID: "y",
    })),
    // [
    //   {
    //     label: "Dataset 1",
    //     data: labels.map(() =>
    //       faker.datatype.number({ min: -1000, max: 1000 })
    //     ),
    //     borderColor: "rgb(255, 99, 132)",
    //     backgroundColor: "rgba(255, 99, 132, 0.5)",
    //     yAxisID: "y",
    //   },
    //   {
    //     label: "Dataset 2",
    //     data: labels.map(() =>
    //       faker.datatype.number({ min: -1000, max: 1000 })
    //     ),
    //     borderColor: "rgb(53, 162, 235)",
    //     backgroundColor: "rgba(53, 162, 235, 0.5)",
    //     yAxisID: "y1",
    //   },
    // ],
  };
  return (
    <div>
      <Line options={options} data={data} />
    </div>
  );
};
const options = {
  responsive: true,
  interaction: {
    mode: "index",
    intersect: false,
  },
  stacked: false,
  plugins: {
    title: {
      display: true,
      text: "Product Price Tracker",
    },
  },
  scales: {
    y: {
      type: "linear",
      display: true,
      position: "left",
    },
    y1: {
      type: "linear",
      display: true,
      position: "right",
      grid: {
        drawOnChartArea: false,
      },
    },
  },
};
